version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mariadb:10.8.3
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .local.env
    networks:
      - memorize-everything-network
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: sh -c "npm i && ./node_modules/.bin/nodemon -L ./index.js"
    networks:
      - memorize-everything-network
    depends_on:
      - db
    environment:
      - ENVFILE=.local.env
networks:
  memorize-everything-network:
    name: memorize-everything-network
    driver: bridge