name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      - run: docker-compose -f docker-compose-test.yml run api_test